# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install uv for faster dependency resolution (optional)
      - pip install uv
    post_install:
      # Install the package with docs dependencies
      - pip install -e .[docs]

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Build additional formats
formats:
  - pdf
  - epub

# Python configuration - simplified approach
python:
  install:
    - requirements: docs/requirements.txt